SELECT 
	A.TZ_PWEI_OPRID,
	A.TZ_SCORE_INS_ID,
    E.TZ_SCORE_NUM,
    F.TZ_DLZH_ID
FROM 
	PS_TZ_CP_PW_KS_TBL A
	LEFT JOIN PS_TZ_KSCLPSLS_TBL B
	ON A.TZ_CLASS_ID=B.TZ_CLASS_ID
	AND A.TZ_APPLY_PC_ID=B.TZ_APPLY_PC_ID
	AND A.TZ_APP_INS_ID=B.TZ_APP_INS_ID
	AND A.TZ_PWEI_OPRID=B.TZ_PWEI_OPRID
	LEFT JOIN PS_TZ_CLPS_GZ_TBL C
	ON A.TZ_CLASS_ID=C.TZ_CLASS_ID
	AND B.TZ_CLPS_LUNC = C.TZ_DQPY_LUNC
	AND A.TZ_APPLY_PC_ID=C.TZ_APPLY_PC_ID
    LEFT JOIN PS_TZ_CJX_TBL E
    ON A.TZ_SCORE_INS_ID=E.TZ_SCORE_INS_ID
    AND E.TZ_SCORE_ITEM_ID=(SELECT F.TZ_HARDCODE_VAL FROM PS_TZ_HARDCD_PNT F WHERE F.TZ_HARDCODE_PNT='TZ_CLPS_ZFCJX_ID')
    LEFT JOIN PS_TZ_AQ_YHXX_TBL F
    ON A.TZ_PWEI_OPRID=F.OPRID
WHERE 
	B.TZ_CLASS_ID = ? 
	AND B.TZ_APPLY_PC_ID = ?
	AND B.TZ_APP_INS_ID = ?
 	AND B.TZ_SUBMIT_YN<>'C'