 select a.TZ_DYNAMIC_FLAG, a.TZ_WEBMAL_FLAG , a.TZ_EMLSERV_ID, a.TZ_MAL_SUBJUECT,a.TZ_MAL_CONTENT, a.TZ_YMB_ID,a.TZ_EML_IF_PRT 
 from PS_TZ_EMALTMPL_TBL a, PS_TZ_TMP_DEFN_TBL b 
 where a.TZ_YMB_ID=b.TZ_YMB_ID and a.TZ_JG_ID=? and a.TZ_TMPL_ID=? 
 ORDER BY a.TZ_KEY_ID limit 0,1