SELECT 
    TZ_MSG_SUBJECT,
    TZ_ZNX_STATUS,
    TZ_MSG_TEXT,
    DATE_FORMAT(ROW_ADDED_DTTM, '%Y-%m-%d %H:%i:%s') AS ROW_ADDED_DTTM
FROM
    PS_TZ_ZNX_MSG_T A
        JOIN
    PS_TZ_ZNX_REC_T B ON (A.TZ_ZNX_MSGID = B.TZ_ZNX_MSGID
        AND B.TZ_REC_DELSTATUS <> 'Y')
        AND A.TZ_ZNX_MSGID = ?
        AND TZ_ZNX_RECID = ?