select 	
	A.TZ_NACT_NAME,
	A.TZ_HD_CS,
    DATE_FORMAT(B.TZ_REG_TIME,'%Y-%m-%d') AS TZ_REG_TIME 
FROM
 PS_TZ_ART_HD_TBL A,PS_TZ_NAUDLIST_T B 
WHERE
 A.TZ_ART_ID = B.TZ_ART_ID AND B.OPRID = ? 
 order by TZ_REG_TIME desc;