Ext.define("KitchenSink.view.tzLianxi.ytt.bugCk.bugAttachmentStore",{
    extend:'Ext.data.Store',
    alias:"store.bugAttachmentStore",
    model:'KitchenSink.view.tzLianxi.ytt.bugCk.bugAttachmentModel',
    tzStoreParams:'',
    pageSize:10,
    autoLoad:false,
    comID:"LX_YTT_BUG_CK_COM",
    pageID:"LX_BUG_INFO_STD1",
    proxy:Ext.tzListProxy()
});