Ext.define("KitchenSink.view.tzLianxi.ytt.bugMg.bugAttachmentStore",{
    extend:'Ext.data.Store',
    alias:"store.bugAttachmentStore",
    model:'KitchenSink.view.tzLianxi.ytt.bugMg.bugAttachmentModel',
    tzStoreParams:'',
    pageSize:10,
    autoLoad:false,
    comID:"LX_YTT_BUG_MG_COM",
    pageID:"LX_BUG_INFO_STD",
    proxy:Ext.tzListProxy()
});