SELECT 
B.TZ_COLU_ID
,A.TZ_ART_ID
,A.TZ_ART_TITLE
,A.TZ_LONG1 AS TZ_ART_ADDR
,month(B.TZ_ART_NEWS_DT) AS TZ_ART_MONTH
,day(B.TZ_ART_NEWS_DT) AS TZ_ART_DAY 
FROM 
PS_TZ_ART_REC_TBL A
INNER JOIN PS_TZ_LM_NR_GL_T B 
	ON(A.TZ_ART_ID=B.TZ_ART_ID AND B.TZ_SITE_ID=? AND B.TZ_ART_PUB_STATE='Y')
INNER JOIN PS_TZ_SITEI_AREA_T C 
	ON (B.TZ_COLU_ID = C.TZ_COLU_ID AND C.TZ_SITEI_ID=B.TZ_SITE_ID AND C.TZ_AREA_ID=?)
WHERE(A.TZ_PROJECT_LIMIT<>'B' OR
	EXISTS (SELECT 1 FROM PS_TZ_ART_AUDIENCE_T AUD
	INNER JOIN PS_TZ_AUD_LIST_T LST ON(AUD.TZ_AUD_ID = LST.TZ_AUD_ID AND LST.OPRID=?)
	WHERE AUD.TZ_ART_ID=A.TZ_ART_ID)) 
ORDER BY B.TZ_ART_SEQ,B.TZ_ART_NEWS_DT DESC LIMIT 4