SELECT 
    TZ_MS_PLAN_SEQ,
    TZ_MSYY_COUNT,
    TZ_MS_DATE,
    DATE_FORMAT(TZ_START_TM, '%H:%i') AS TZ_START_TM,
    DATE_FORMAT(TZ_END_TM, '%H:%i') AS TZ_END_TM,
    TZ_MS_LOCATION,
    TZ_MS_ARR_DEMO,
    TZ_MS_PUB_STA,
    TZ_MS_OPEN_STA,
    (SELECT 
            COUNT(1)
        FROM
            PS_TZ_MSYY_KS_TBL
        WHERE
            TZ_CLASS_ID = A.TZ_CLASS_ID
                AND TZ_BATCH_ID = A.TZ_BATCH_ID
                AND TZ_MS_PLAN_SEQ = A.TZ_MS_PLAN_SEQ) AS TZ_YY_COUNT
FROM
    PS_TZ_MSSJ_ARR_TBL A
WHERE
    TZ_CLASS_ID = ?
        AND TZ_BATCH_ID = ?
ORDER BY TZ_MS_DATE ASC
LIMIT ? , ?