SELECT
	A.TZ_APP_INS_ID,
	group_concat(A.TZ_SCORE_INS_ID) AS TZ_SCORE_INS_IDS
FROM
	PS_TZ_MP_PW_KS_TBL A
WHERE
	A.TZ_CLASS_ID = ?
AND A.TZ_APPLY_PC_ID = ?
AND A.TZ_SCORE_INS_ID IS NOT NULL
GROUP BY
	A.TZ_APP_INS_ID