SELECT
	ATTACHSYSFILENAME,
	ATTACHUSERFILE,
	TZ_ACCESS_PATH
FROM
	PS_TZ_FORM_ATT_T
WHERE
	TZ_APP_INS_ID =?
AND TZ_XXX_BH IN (
	SELECT
		TEMP.TZ_XXX_BH
	FROM
		PS_TZ_TEMP_FIELD_T TEMP,
		PS_TZ_APP_XXXPZ_T APP
	WHERE
		TEMP.TZ_APP_TPL_ID = APP.TZ_APP_TPL_ID
	AND TEMP.TZ_XXX_NO = APP.TZ_XXX_BH
	AND APP.TZ_APP_TPL_ID = (
		SELECT
			C.TZ_APP_TPL_ID
		FROM
			PS_TZ_APP_INS_T C
		WHERE
			C.TZ_APP_INS_ID =?
	)
	AND APP.TZ_IS_DOWNLOAD = 'Y'
)
UNION
	SELECT
		ATTACHSYSFILENAME,
		ATTACHUSERFILE,
		TZ_ACCESS_PATH
	FROM
		PS_TZ_FORM_ATT_T
	WHERE
		TZ_APP_INS_ID =?
	AND TZ_XXX_BH IN (
		SELECT
			TZ_XXX_BH
		FROM
			PS_TZ_FORM_ATT2_T
		WHERE
			TZ_APP_INS_ID =?
	)
UNION
SELECT
	X.TZ_ATTACHSYSFILENA AS ATTACHSYSFILENAME,
	X.TZ_ATTACHFILE_NAME AS ATTACHUSERFILE,
	X.TZ_ATT_A_URL AS TZ_ACCESS_PATH
FROM
	PS_TZ_OPR_PHOTO_T X,
	PS_TZ_FORM_WRK_T A,
	PS_TZ_OPR_PHT_GL_T B
WHERE
	A.TZ_APP_INS_ID =?
AND A.OPRID = B.OPRID
AND B.TZ_ATTACHSYSFILENA = X.TZ_ATTACHSYSFILENA		