SELECT
	c.TZ_CLASS_ID as classid,
	c.TZ_APPLY_PC_ID as pcid,
	c.TZ_APP_INS_ID as insid,
	e.TZ_REALNAME as name,
	(b.TZ_ATT_A_URL + b.TZ_ATTACHSYSFILENA) as photo,
	f.TZ_COMPANY_NAME as COMPANY,
	f.TZ_COMMENT1 as postion,
	d.OPRID as oprid,
	c.TZ_SCORE_INS_ID as scoreid,
	h.TZ_GROUP_SPACE as SPACE
FROM
	ps_TZ_MP_PW_KS_TBL c
LEFT JOIN ps_tz_form_wrk_t d ON (
	c.TZ_APP_INS_ID = d.TZ_APP_INS_ID
)
LEFT JOIN PS_TZ_OPR_PHT_GL_T a ON d.OPRID = a.OPRID
LEFT JOIN PS_TZ_OPR_PHOTO_T b ON a.TZ_ATTACHSYSFILENA = b.TZ_ATTACHSYSFILENA
LEFT JOIN PS_TZ_AQ_YHXX_TBL e ON e.OPRID = d.OPRID
LEFT JOIN PS_TZ_REG_USER_T f ON f.OPRID = d.OPRID
INNER JOIN PS_TZ_MSPS_KSH_TBL g ON (
	c.TZ_CLASS_ID = g.TZ_CLASS_ID
	AND c.TZ_APPLY_PC_ID = g.TZ_APPLY_PC_ID
	AND c.TZ_APP_INS_ID = g.TZ_APP_INS_ID
)
LEFT JOIN TZ_INTERVIEW_GROUP h ON (
	h.TZ_CLASS_ID = g.TZ_CLASS_ID
	AND h.TZ_APPLY_PC_ID = g.TZ_APPLY_PC_ID
	AND h.TZ_GROUP_ID = g.TZ_GROUP_ID
)
WHERE
	c.TZ_PWEI_OPRID = ?
AND c.TZ_CLASS_ID = ?
AND c.TZ_APPLY_PC_ID = ?
AND (c.TZ_DELETE_ZT<>'Y' OR c.TZ_DELETE_ZT IS NULL)
ORDER BY h.TZ_GROUP_SPACE ASC