SELECT A.TZ_APP_INS_ID,
	   A.TZ_SCORE_INS_ID,	
	   E.TZ_ORDER,
	   B.OPRID,
	   C.TZ_MSH_ID,
	   IFNULL(D.TZ_REALNAME,C.TZ_REALNAME) TZ_REALNAME,
	   D.TZ_GENDER,
	   (SELECT X.TZ_ZHZ_CMS FROM PS_TZ_PT_ZHZXX_TBL X WHERE X.TZ_ZHZ_ID=D.TZ_GENDER AND X.TZ_ZHZJH_ID='TZ_GENDER') TZ_GENDER_DESC
FROM PS_TZ_MP_PW_KS_TBL A,
	 PS_TZ_MSPS_KSH_TBL E,
	 PS_TZ_FORM_WRK_T B,
	 PS_TZ_AQ_YHXX_TBL C,
	 PS_TZ_REG_USER_T D
WHERE A.TZ_APP_INS_ID=B.TZ_APP_INS_ID 
AND B.OPRID=C.OPRID 
AND B.OPRID=D.OPRID
AND C.TZ_RYLX='ZCYH'
AND A.TZ_CLASS_ID=E.TZ_CLASS_ID 
AND A.TZ_APPLY_PC_ID=E.TZ_APPLY_PC_ID 
AND A.TZ_APP_INS_ID=E.TZ_APP_INS_ID
AND E.TZ_GROUP_ID=?
AND A.TZ_CLASS_ID=? 
AND A.TZ_APPLY_PC_ID=? 
AND A.TZ_PWEI_OPRID=?
ORDER BY E.TZ_ORDER ASC