SELECT
	C.TZ_CLASS_ID AS classid,
	C.TZ_APPLY_PC_ID AS pcid,
	C.TZ_APP_INS_ID AS insid,
	E.TZ_REALNAME AS NAME,
	(
		B.TZ_ATT_A_URL + B.TZ_ATTACHSYSFILENA
	) AS photo,
	F.TZ_COMPANY_NAME AS COMPANY,
	F.TZ_COMMENT1 AS postion,
	D.OPRID AS oprid,
	C.TZ_SCORE_INS_ID AS scoreid,
	M.TZ_MS_PLAN_SEQ AS SPACE
FROM
	PS_TZ_MP_PW_KS_TBL C
LEFT JOIN PS_TZ_FORM_WRK_T D ON (
	C.TZ_APP_INS_ID = D.TZ_APP_INS_ID
)
LEFT JOIN PS_TZ_OPR_PHT_GL_T A ON D.OPRID = A.OPRID
LEFT JOIN PS_TZ_OPR_PHOTO_T B ON A.TZ_ATTACHSYSFILENA = B.TZ_ATTACHSYSFILENA
LEFT JOIN PS_TZ_AQ_YHXX_TBL E ON E.OPRID = D.OPRID
LEFT JOIN PS_TZ_REG_USER_T F ON F.OPRID = D.OPRID
INNER JOIN PS_TZ_MSPS_KSH_TBL G ON (
	C.TZ_CLASS_ID = G.TZ_CLASS_ID
	AND C.TZ_APPLY_PC_ID = G.TZ_APPLY_PC_ID
	AND C.TZ_APP_INS_ID = G.TZ_APP_INS_ID
)
LEFT JOIN PS_TZ_MSYY_KS_TBL M ON (
	M.TZ_CLASS_ID = C.TZ_CLASS_ID
	AND M.TZ_BATCH_ID = C.TZ_APPLY_PC_ID
	AND M.OPRID = D.OPRID
)
WHERE
	C.TZ_PWEI_OPRID = ?
AND C.TZ_CLASS_ID = ?
AND C.TZ_APPLY_PC_ID = ?
AND (
	C.TZ_DELETE_ZT <> 'Y'
	OR C.TZ_DELETE_ZT IS NULL
)