SELECT DISTINCT A.TREE_NODE 
 ,A.PARENT_NODE_NAME 
 ,C.TZ_XS_MC 
 ,B.TZ_SCORE_ITEM_TYPE 
 ,( 
 SELECT 'Y' 
  FROM PSTREENODE C 
 WHERE C.TREE_NAME=A.TREE_NAME 
   AND C.TREE_NODE_NUM>A.TREE_NODE_NUM 
   AND C.TREE_NODE_NUM_END<A.TREE_NODE_NUM_END  LIMIT 1) TZ_NO_LEAF, A.TREE_LEVEL_NUM,B.TZ_SCORE_LIMITED,
   B.TZ_SCORE_LIMITED2,B.TZ_SCORE_PY_ZSLIM,B.TZ_SCORE_PY_ZSLIM0,B.TZ_SCORE_ITEM_DFSM,
   B.TZ_SCORE_ITEM_CKWT,B.TZ_SCORE_ITEM_MSFF,B.TZ_SCORE_HZ,B.TZ_SCORE_QZ,B.TZ_SCR_SQZ,B.TZ_SCR_TO_SCORE
  FROM PSTREENODE A,PS_TZ_MODAL_DT_TBL B,PS_TZ_CJ_BPH_TBL C,PS_TZ_RS_MODAL_TBL D 
 WHERE A.TREE_NAME=B.TREE_NAME 
   AND A.TREE_NODE=B.TZ_SCORE_ITEM_ID 
   AND B.TZ_SCORE_ITEM_ID = C.TZ_SCORE_ITEM_ID 
   AND C.TZ_ITEM_S_TYPE='A'
   AND C.TZ_SCORE_MODAL_ID=D.TZ_SCORE_MODAL_ID
   AND A.TREE_NAME=D.TREE_NAME
   AND D.TZ_SCORE_MODAL_ID=?
  ORDER BY C.TZ_PX ASC,A.TREE_NODE_NUM,A.TREE_NODE_NUM_END DESC