SELECT A.TZ_APP_INS_ID,AVG(E.TZ_SCORE_NUM) AS TZ_SCORE
 	FROM PS_TZ_MP_PW_KS_TBL A ,
 		 PS_TZ_SRMBAINS_TBL B,
 		 PS_TZ_RS_MODAL_TBL C,
		 PSTREENODE D,
 		 PS_TZ_CJX_TBL E
	WHERE A.TZ_SCORE_INS_ID=B.TZ_SCORE_INS_ID 
	AND B.TZ_SCORE_MODAL_ID=C.TZ_SCORE_MODAL_ID
	AND D.TREE_NAME=C.TREE_NAME 
	AND D.PARENT_NODE_NUM=0 
    AND E.TZ_SCORE_INS_ID=A.TZ_SCORE_INS_ID 
	AND E.TZ_SCORE_ITEM_ID=D.TREE_NODE
	AND C.TZ_JG_ID=?
	AND A.TZ_CLASS_ID=? 
	AND A.TZ_APPLY_PC_ID=?
	AND A.TZ_DELETE_ZT<>'Y'
	AND EXISTS(
		SELECT 1 FROM PS_TZ_MSPWPSJL_TBL 
		WHERE TZ_APPLY_PC_ID=A.TZ_APPLY_PC_ID 
			  AND TZ_CLASS_ID=A.TZ_CLASS_ID 
			  AND TZ_PWEI_OPRID=A.TZ_PWEI_OPRID 
			  /*AND TZ_SUBMIT_YN='Y'*/
	) GROUP BY A.TZ_APP_INS_ID