SELECT
	Z.*,
IF (
	@objno = Z.TREE_NAME
	OR (
		@objno IS NULL
		AND Z.TREE_NAME IS NULL
	),
	@rank :=@rank + 1,
	@rank := 1
) AS XUHAO,
 @objno := Z.TREE_NAME
FROM
	(
		SELECT
			A.TZ_APP_INS_ID,
			A.TZ_SCORE_INS_ID,
			B.TZ_SCORE_MODAL_ID,
			C.TREE_NAME,
			D.TREE_NODE,
			E.TZ_SCORE_NUM
		FROM
			PSTREENODE D,
			PS_TZ_MP_PW_KS_TBL A,
			PS_TZ_SRMBAINS_TBL B,
			PS_TZ_RS_MODAL_TBL C,
			PS_TZ_CJX_TBL E
		WHERE
			A.TZ_SCORE_INS_ID = B.TZ_SCORE_INS_ID
		AND B.TZ_SCORE_MODAL_ID = C.TZ_SCORE_MODAL_ID
		AND D.TREE_NAME = C.TREE_NAME
		AND D.PARENT_NODE_NUM = 0
		AND E.TZ_SCORE_INS_ID = A.TZ_SCORE_INS_ID
		AND E.TZ_SCORE_ITEM_ID = D.TREE_NODE
		AND C.TZ_JG_ID = ?
		AND A.TZ_CLASS_ID = ?
		AND A.TZ_APPLY_PC_ID = ?
		AND A.TZ_PWEI_OPRID = ?
		AND A.TZ_DELETE_ZT <> 'Y'
		ORDER BY
			C.TREE_NAME,
			E.TZ_SCORE_NUM DESC
	) Z,
	(
		SELECT
			@objno := NULL ,@rank := 0
	) b;、