Ext.define('KitchenSink.view.clueManagement.clueManagement.clueProblemModel',{
    extend:'Ext.data.Model',
    fields:[
        {name:'clueId'},
        {name:'wtType'},
        {name:'clueDesc'},
        {name:'name'},
        {name:'mobile'},
        {name:'company'},
        {name:'createWay'},
        {name:'createWayDesc'},
        {name:'localName'},
        {name:'createDttm',type:'date',dateFormat:'Y-m-d H:i'},
        {name:'chargeOprid'},
        {name:'chargeName'},
        {name:'suggestOperation'},
        {name:'systemRuleTip'},
        {name:'isChecked'}
    ]
});
