SELECT
	A.TZ_GROUP_ID,
	date_format(
		A.TZ_GROUP_DATE,
		'%Y-%m-%d %H:%I:%S'
	) AS TZ_GROUP_DATE,
	A.TZ_ORDER,
	B.TZ_GROUP_NAME,
	B.TZ_CLPS_GR_ID,
	C.TZ_CLPS_GR_NAME
FROM
	PS_TZ_MSPS_KSH_TBL A,
	PS_TZ_INTEGROUP_T B,
	PS_TZ_MSPS_GR_TBL C
WHERE
	A.TZ_GROUP_ID = B.TZ_GROUP_ID
AND B.TZ_CLPS_GR_ID=C.TZ_CLPS_GR_ID
AND A.TZ_CLASS_ID =?
AND A.TZ_APPLY_PC_ID =?
AND A.TZ_APP_INS_ID =?