SELECT
   A.TZ_PWEI_OPRID,
	D.TZ_DLZH_ID,
	A.TZ_KSH_PSPM,
	C.TZ_CLPS_GR_NAME,
    A.TZ_SCORE_INS_ID
FROM
	PS_TZ_MP_PW_KS_TBL A,
	PS_TZ_MSPS_PW_TBL B,
	PS_TZ_MSPS_GR_TBL C,
  PS_TZ_AQ_YHXX_TBL D
WHERE
	A.TZ_CLASS_ID = B.TZ_CLASS_ID
AND A.TZ_APPLY_PC_ID = B.TZ_APPLY_PC_ID
AND A.TZ_PWEI_OPRID = B.TZ_PWEI_OPRID
AND C.TZ_CLPS_GR_ID = B.TZ_PWEI_GRPID
AND D.OPRID=A.TZ_PWEI_OPRID
AND A.TZ_DELETE_ZT <> 'Y'
AND A.TZ_PSHEN_ZT <> 'C'
AND A.TZ_APPLY_PC_ID =?
AND A.TZ_APP_INS_ID =?
AND A.TZ_CLASS_ID =?