SELECT
	A.TZ_PWEI_GRPID,
	F.TZ_SCORE_NUM
FROM
	PS_TZ_MSPS_PW_TBL A
JOIN PS_TZ_MP_PW_KS_TBL B ON A.TZ_APPLY_PC_ID = B.TZ_APPLY_PC_ID
AND A.TZ_CLASS_ID = B.TZ_CLASS_ID
AND A.TZ_PWEI_OPRID = B.TZ_PWEI_OPRID
LEFT JOIN PS_TZ_SRMBAINS_TBL C ON B.TZ_SCORE_INS_ID = C.TZ_SCORE_INS_ID
LEFT JOIN PS_TZ_RS_MODAL_TBL D ON C.TZ_SCORE_MODAL_ID = D.TZ_SCORE_MODAL_ID
AND D.TZ_JG_ID = ?
AND D.TZ_MODAL_FLAG <> 'N'
LEFT JOIN PSTREENODE E ON E.TREE_NAME = D.TREE_NAME
AND E.PARENT_NODE_NUM = 0
LEFT JOIN PS_TZ_CJX_TBL F ON F.TZ_SCORE_INS_ID = B.TZ_SCORE_INS_ID
AND F.TZ_SCORE_ITEM_ID = E.TREE_NODE
WHERE
	B.TZ_CLASS_ID = ?
AND B.TZ_APPLY_PC_ID = ?
AND B.TZ_APP_INS_ID = ?
AND B.TZ_PWEI_OPRID = ?