SELECT C.TZ_SCORE_ITEM_ID,C.DESCR FROM
PS_TZ_MP_PW_KS_TBL A,
PS_TZ_SRMBAINS_TBL B,
PS_TZ_MODAL_DT_TBL C,
PSTREENODE D 
WHERE B.TZ_SCORE_INS_ID=A.TZ_SCORE_INS_ID
AND B.TZ_SCORE_MODAL_ID=D.TREE_NAME
AND C.TREE_NAME=D.TREE_NAME
AND C.TZ_SCORE_ITEM_ID=D.TREE_NODE
AND A.TZ_APP_INS_ID=?
ORDER BY D.TREE_NODE_NUM