SELECT DISTINCT C.TZ_SCORE_ITEM_ID,C.DESCR FROM
PS_TZ_MP_PW_KS_TBL A,
PS_TZ_SRMBAINS_TBL B,
PS_TZ_MODAL_DT_TBL C,
PSTREENODE D ,
PS_TZ_RS_MODAL_TBL E
WHERE B.TZ_SCORE_INS_ID=A.TZ_SCORE_INS_ID
AND E.TZ_SCORE_MODAL_ID=B.TZ_SCORE_MODAL_ID
AND D.TREE_NAME=E.TREE_NAME
AND E.TREE_NAME=C.TREE_NAME
AND C.TZ_SCORE_ITEM_ID=D.TREE_NODE
AND A.TZ_APP_INS_ID=?
AND E.TZ_JG_ID=?
AND E.TZ_MODAL_FLAG<>'N'
ORDER BY D.TREE_NODE_NUM