SELECT
	D.TZ_SCORE_NUM
FROM
	PS_TZ_CP_PW_KS_TBL A,
	PS_TZ_SRMBAINS_TBL B,
	PS_TZ_MODAL_DT_TBL C,
	PS_TZ_CJX_TBL D
WHERE
	A.TZ_SCORE_INS_ID = B.TZ_SCORE_INS_ID
AND B.TZ_SCORE_MODAL_ID = C.TREE_NAME
AND D.TZ_SCORE_ITEM_ID = C.TZ_SCORE_ITEM_ID
AND D.TZ_SCORE_INS_ID = A.TZ_SCORE_INS_ID
AND C.TZ_SCORE_ITEM_ID = 'Total'
AND A.TZ_APP_INS_ID=?