SELECT
	D.TZ_SCORE_NUM,
	D.TZ_SCORE_ITEM_ID
FROM
	PS_TZ_MP_PW_KS_TBL A,
	PS_TZ_SRMBAINS_TBL B,
	PS_TZ_MODAL_DT_TBL C,
	PS_TZ_CJX_TBL D
WHERE
	A.TZ_SCORE_INS_ID = B.TZ_SCORE_INS_ID
AND C.TREE_NAME = B.TZ_SCORE_MODAL_ID
AND D.TZ_SCORE_ITEM_ID = C.TZ_SCORE_ITEM_ID
AND A.TZ_SCORE_INS_ID = D.TZ_SCORE_INS_ID
AND A.TZ_APP_INS_ID =?
AND A.TZ_PWEI_OPRID =?