SELECT
	D.TZ_SCORE_NUM,
	D.TZ_SCORE_ITEM_ID
FROM
	PS_TZ_MP_PW_KS_TBL A,
	PS_TZ_CJX_TBL D,
  PS_TZ_FORM_WRK_T B
WHERE D.TZ_SCORE_INS_ID = A.TZ_SCORE_INS_ID
AND A.TZ_APP_INS_ID=B.TZ_APP_INS_ID
AND A.TZ_CLASS_ID=B.TZ_CLASS_ID
AND A.TZ_APPLY_PC_ID=B.TZ_BATCH_ID
AND B.TZ_APP_INS_ID =?
AND A.TZ_PWEI_OPRID =?