/**
 * 根据OPRID查询时候存在报考的年份的次数大于三
 * COUNT
 */
SELECT COUNT(DISTINCT A.TZ_APP_INS_ID) CNT
   FROM PS_TZ_FORM_WRK_T A,
        PS_TZ_CLASS_INF_T B
   WHERE A.OPRID = ?
     AND A.TZ_CLASS_ID = B.TZ_CLASS_ID
     and B.TZ_PRJ_ID IN (  select A1.TZ_PRJ_ID from PS_TZ_PRJ_INF_T A1,PS_TZ_PROJECT_SITE_T A2
     WHERE A1.TZ_PRJ_ID=A2.TZ_PRJ_ID and A2.TZ_SITEI_ID IN (SELECT B3.TZ_SITEI_ID FROM PS_TZ_CLASS_INF_T B1,PS_TZ_PRJ_INF_T B2,PS_TZ_PROJECT_SITE_T B3
     WHERE B1.TZ_JG_ID=B2.TZ_JG_ID AND B1.TZ_PRJ_ID=B2.TZ_PRJ_ID AND B2.TZ_PRJ_ID=B3.TZ_PRJ_ID 
     AND B1.TZ_CLASS_ID=?))