Ext.define("KitchenSink.view.bugManagement.bugCk.bugCkAttachmentStore",{
    extend:'Ext.data.Store',
    alias:"store.bugAttachmentStore",
    model:'KitchenSink.view.bugManagement.bugCk.bugCkAttachmentModel',
    tzStoreParams:'',
    pageSize:10,
    autoLoad:false,
    comID:"TZ_BUGCK_COM",
    pageID:"TZ_BUG_INFO_STD1",
    proxy:Ext.tzListProxy()
});