SELECT COUNT(1) FROM PS_TZ_APP_XXXPZ_T A 
WHERE NOT EXISTS(
	SELECT * FROM PS_TZ_APP_XXXPZ_T X
	WHERE A.TZ_APP_TPL_ID = X.TZ_APP_TPL_ID AND X.TZ_COM_LMC <> 'Page' AND X.TZ_XXX_BT_BZ = 'Y'
	AND A.TZ_PAGE_NO = X.TZ_PAGE_NO
	AND TZ_XXX_SLID <> 'EngLevelUp'
) AND A.TZ_APP_TPL_ID = ? AND A.TZ_COM_LMC = 'Page' AND TZ_XXX_BH = ?