SELECT TMP.TZ_APP_S_TEXT 
 ,TMP.TZ_COM_LMC 
  FROM ( 
 SELECT A.TZ_APP_INS_ID 
 , A.TZ_APP_TPL_ID 
 , A.TZ_D_XXX_BH 
 , A.TZ_APP_S_TEXT 
 , A.TZ_APP_L_TEXT 
 ,A.TZ_COM_LMC 
 , ROW_NUMBER() OVER (PARTITION BY A.TZ_APP_INS_ID 
 ,A.TZ_APP_TPL_ID 
 , A.TZ_D_XXX_BH 
  ORDER BY A.TZ_XXX_BH) TMP_SEQ 
  FROM PS_TZ_APP_CC_VW2 A 
 WHERE TZ_APP_INS_ID = ? 
   AND TZ_D_XXX_BH = ? 
   AND TZ_XXX_BH LIKE ? 
   AND TZ_XXX_NO = ?) TMP 
 WHERE TMP_SEQ = ?