Ext.define("KitchenSink.view.bugManagement.bugMg.bugAttachmentStore",{
    extend:'Ext.data.Store',
    alias:"store.bugAttachmentStore",
    model:'KitchenSink.view.bugManagement.bugMg.bugAttachmentModel',
    tzStoreParams:'',
    pageSize:10,
    autoLoad:false,
    comID:"TZ_BUGMG_COM",
    pageID:"TZ_BUG_INFO_STD",
    proxy:Ext.tzListProxy()
});