SELECT A.TZ_LEAD_ID,
	   A.TZ_THYY_ID,
	   B.TZ_LABEL_NAME TZ_THYY_NAME,
	   A.TZ_GBYY_ID,
	   C.TZ_LABEL_NAME TZ_GBYY_NAME,
       A.TZ_COLOUR_SORT_ID,
       D.TZ_COLOUR_NAME,
       D.TZ_COLOUR_CODE
FROM PS_TZ_XSXS_INFO_T A LEFT JOIN PS_TZ_THYY_XSGL_T B
     ON A.TZ_THYY_ID=B.TZ_THYY_ID
     LEFT JOIN PS_TZ_GBYY_XSGL_T C
     ON A.TZ_GBYY_ID=C.TZ_GBYY_ID
     LEFT JOIN PS_TZ_XSXS_XSLB_T D
     ON A.TZ_COLOUR_SORT_ID=D.TZ_COLOUR_SORT_ID
WHERE A.TZ_LEAD_ID=?